_wandb:
    value:
        cli_version: 0.19.0
        m: []
        python_version: 3.10.15
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 55
                - 71
                - 83
            "2":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 55
                - 71
                - 83
            "3":
                - 23
                - 55
                - 61
            "4": 3.10.15
            "5": 0.19.0
            "6": 4.47.0
            "8":
                - 5
            "12": 0.19.0
            "13": linux-x86_64
adam_beta1:
    value: 0.9
adam_beta2:
    value: 0.999
adam_epsilon:
    value: 1e-08
adam_weight_decay:
    value: 0.01
allow_tf32:
    value: false
cache_dir:
    value: null
caption_column:
    value: text
checkpointing_steps:
    value: 5000
checkpoints_total_limit:
    value: null
conditioning_image_column:
    value: conditioning_image
controlnet_model_name_or_path:
    value: null
dataloader_num_workers:
    value: 0
dataset_config_name:
    value: null
dataset_name:
    value: null
enable_xformers_memory_efficient_attention:
    value: true
gradient_accumulation_steps:
    value: 4
gradient_checkpointing:
    value: false
hub_model_id:
    value: null
hub_token:
    value: null
image_column:
    value: image
learning_rate:
    value: 1e-05
logging_dir:
    value: logs
lr_num_cycles:
    value: 1
lr_power:
    value: 1
lr_scheduler:
    value: constant
lr_warmup_steps:
    value: 500
max_grad_norm:
    value: 1
max_train_samples:
    value: null
max_train_steps:
    value: 18750
mixed_precision:
    value: "no"
num_train_epochs:
    value: 3
num_validation_images:
    value: 4
output_dir:
    value: model_out
pretrained_model_name_or_path:
    value: CompVis/stable-diffusion-v1-4
proportion_empty_prompts:
    value: 0
push_to_hub:
    value: true
report_to:
    value: wandb
resolution:
    value: 512
resume_from_checkpoint:
    value: null
revision:
    value: null
scale_lr:
    value: false
seed:
    value: null
set_grads_to_none:
    value: false
tokenizer_name:
    value: null
tracker_project_name:
    value: controlnet
train_batch_size:
    value: 1
train_data_dir:
    value: /data/datasets/20241122/fusing-fill50k/fill50k_data/train
use_8bit_adam:
    value: false
validation_steps:
    value: 5000
variant:
    value: null
