  - case_name: model.infer.async.yolov5s.1card.shape640*640
    onnx_path: /mnt/test_models/onnx_models/CV/dynamic_yolov5/yolov5s_float_dyn.onnx
    pass_path: yolov5m/yolov5_pass.py
    onnx_dtype: float16
    input_shapes: 1*3*640*640
    batch_size: [1,4,8,16,32,64,128,256,512]
    iterations: 50
    warm_up: 10
    run_sync: 0
    cuda_throughput: [644.952000]
    cuda_latency: [0.0020815]
    history_throughput:
    history_latency:
    desc:
      dataset: coco
      shape: 640*640
