metric: COCO
num_classes: 80

TrainDataset:
  name: COCODataSet
  # image_dir: train2017
  image_dir: train
  # anno_path: annotations/instances_train2017.json
  anno_path: ../annotations/instances_train2017.json
  dataset_dir: /root/data/datasets/COCO/images
  data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  name: COCODataSet
  # image_dir: val2017
  image_dir: val
  # anno_path: annotations/instances_val2017.json
  anno_path: ../annotations/instances_val2017.json
  dataset_dir: /root/data/datasets/COCO/images
  allow_empty: true

TestDataset:
  name: ImageFolder
  anno_path: annotations/instances_val2017.json # also support txt (like VOC's label_list.txt)
  dataset_dir: /root/data/datasets/COCO # if set, anno_path will be 'dataset_dir/anno_path'
