- case_name: ssd
  run_dir: TecoInference/contrib/detection/ssd
  run_export:
    run_file: export_onnx.py
    params:
      ckpt: /mnt/nvme/common/user_data/yqw/ssd/mobilenet_v3_ssd320_voc0712.pth
  run_example_valid:
    run_file: example_valid.py
    params:
      ckpt: ssd_dyn_float16.onnx
      batch_size: 4
      data_path: /mnt/nvme/common/train_dataset/voc/VOC2007
      target: sdaa
      dtype: float16
      others:
        input_size: 320
        num_workers: 1
        verbose: False
  run_example_single:
    run_file: example_single_batch.py
    params:
      ckpt: ssd_dyn_float16.onnx
      batch_size: 1
      data_path: ./images/humandog.jpg
      target: sdaa
      dtype: float16
      others:
        input_size: 320
        conf_thres: 0.2
  run_example_multi:
    run_file: example_multi_batch.py
    params:
      ckpt: ssd_dyn_float16.onnx
      batch_size: 1
      data_path: ./images
      target: sdaa
      dtype: float16
      others:
        input_size: 320
        conf_thres: 0.2
